import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  const redirect_uri = "http://localhost:3000/api/auth/redirect";
  const signinURL = `https://qa.yext.com/oauth2/authorize?client_id=5030425fe15c4077936faed801dec537&redirect_uri=${redirect_uri}&scope=openid%20profile&response_type=code&response_mode=query&nonce=1emd3xgvt69`;
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Sign In with Yext Demo</h1>
      <p>You are not currently logged in. Sign in below to continue.</p>
      <a href={signinURL}>Sign In</a>
    </div>
  );
};

export default Home;
